/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define CONFIG_HVF 1

#define CONFIG_SOFTMMU 1

#define CONFIG_SYSTEM_ONLY 1

#define CONFIG_TCG 1

#define TARGET_AARCH64 1

#define TARGET_ARCH AARCH64

#define TARGET_ARM 1

#define TARGET_BIG_ENDIAN 0

#define TARGET_KVM_HAVE_GUEST_DEBUG 1

#define TARGET_LONG_BITS 64

#define TARGET_NAME "aarch64"

#define TARGET_NEED_FDT 1

#define TARGET_NOT_USING_LEGACY_LDST_PHYS_API 1

