# Automatically generated by configure - do not modify

all:
SRC_PATH=/Users/steve372dzudo/src/qemu-11.0.1
TARGET_DIRS=x86_64-softmmu i386-softmmu aarch64-softmmu arm-softmmu riscv64-softmmu ppc-softmmu ppc64-softmmu
GDB=
SUBDIRS=
PYTHON=/Users/steve372dzudo/src/qemu-11.0.1/build-sanaka/pyvenv/bin/python3.14 -B
MKVENV_ENSUREGROUP=/Users/steve372dzudo/src/qemu-11.0.1/build-sanaka/pyvenv/bin/python3.14 -B /Users/steve372dzudo/src/qemu-11.0.1/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=/opt/homebrew/bin/mkisofs
MESON=/Users/steve372dzudo/src/qemu-11.0.1/build-sanaka/pyvenv/bin/meson
NINJA=/opt/homebrew/bin/ninja
EXESUF=
TCG_TESTS_WITH_COMPILERS=
