#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later

exec /Users/steve372dzudo/src/qemu-11.0.1/build-sanaka/pyvenv/bin/meson devenv -C /Users/steve372dzudo/src/qemu-11.0.1/build-sanaka -w "$PWD" "$@"
